# Use an existing docker image as a base
FROM eclipse-mosquitto:latest

# Tell the image what to do when it starts as a container 
CMD ["/usr/sbin/mosquitto", "-c", "/mosquitto/config/mosquitto.conf"]